name: Build

on:
  push:
    branches:
      - export

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connecting to Informatica Repository
        run: |
          # Assuming pmrep is available on your self-hosted runner and in PATH
          echo "Connecting to Informatica Repository"
          pmrep connect -r DEV_REP -d DOM_DEV -n om -x om

      - name: Export workflow
        run: |
          echo "Exporting workflow:"
          pmrep objectexport -n wf_first_workflow -o workflow -f Original -m -s -b -r -u /path/to/export/wf_first_workflow.xml
