name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Informatica CLI
        run: |
          # Assuming pmrep is available on your self-hosted runner and in PATH
          cd C:\Informatica\9.6.1\server\bin
          echo "Connecting to Informatica Repository"
          pmrep connect -r DEV_REP -d DOM_DEV -n om -x om
          pmrep objectexport -n wf_first_workflow -o workflow -f Original -m -s -b -r -u C:\Users\infa_admin\Desktop\export\wf_first_workflow.xml
          
